import { lazy } from "react"

export const About = lazy(() => import('./components/About/About')) 
export const AboutInstructor = lazy(() => import('./components/About/AboutInstructor')) 
export const AddCategory = lazy(() => import('./components/AdminStuff/AddCategory/AddCategory')) 
export const AddCourse = lazy(() => import('./components/AdminStuff/AddCourse/AddCourse')) 
export const AddInstructor = lazy(() => import('./components/AdminStuff/AddInstructor/AddInstructor')) 
export const AddRole = lazy(() => import('./components/AdminStuff/AddRole/AddRole')) 
export const ListAdminCourses = lazy(() => import('./components/AdminStuff/Courses/ListAdminCourses')) 
export const CourseDetailsAdmin = lazy(() => import('./components/AdminStuff/CoursesDetails/CourseDetailsAdmin')) 
export const GuestChat = lazy(() => import('./components/AdminStuff/GuestChat/GuestChat')) 
export const ListOfUsers = lazy(() => import('./components/AdminStuff/ListUsers/ListOfUsers'))
export const SendEmailSubs = lazy(() => import('./components/AdminStuff/SendEmails/SendEmailSubs'))
export const CourseDetails = lazy(() => import('./components/CourseDetails/CourseDetails'))
export const DoesntExistPage = lazy(() => import('./components/DoesntExist/DoesntExistPage'))
export const Homescreen = lazy(() => import('./components/Homescreen/Homescreen')) 
export const CoursesList = lazy(() => import('./components/ListOfCourses/CoursesList')) 
export const DashBoard = lazy(() => import('./components/MainPage/DashBoard')) 
export const Layout = lazy(() => import('./components/MainPage/Mainpage')) 
export const MainPage = lazy(() => import('./components/MainPage/Mainpage')) 
export const Mainpage = lazy(() => import('./components/MainPage/Mainpage')) 
export const MyCourses = lazy(() => import('./components/MyCourses/MyCourses')) 
export const RootLayout = lazy(() => import('./components/RootLayout/RootLayout')) 
export const Register = lazy(() => import('./components/RegisterAndLogin/Register'))
export const Unsubscribe = lazy(() => import('./components/Unsubscribe/Unsubscribe')) 
export const VerifyAccountToken = lazy(() => import('./components/VerifyAccountToken/VerifyAccountToken')) 
export const WatchLectures = lazy(() => import('./components/WatchLectures/WatchLectures'))
export const Login = lazy(() => import('./components/RegisterAndLogin/Login'))
export const AddBadges = lazy(() => import('./components/AdminStuff/AddBadges/AddBadges'))
export const ListBadges = lazy(() => import('./components/AdminStuff/ListBadges/ListBadges'))
export const AddRequirmentTypeBadgeLazy = lazy(() => import('./components/AdminStuff/AddBridgeCriteria/AddRequirmentTypeBadge'))
export const AddBridgeCriteriaLazy = lazy(() => import('./components/AdminStuff/AddBridgeCriteria/AddBridgeCriteria'))
export const CreateQuizzLazy = lazy(() => import('./components/AdminStuff/CreateQuizz/CreateQuizz'));
export const QuizzListLazy = lazy(() => import('./components/AdminStuff/QuizzList/QuizzList'))
// export const NewRegister = lazy(() => import('./components/Register/Register'))
